CREATE TABLE Stg_Beneficiary (
    DESYNPUF_ID VARCHAR(255),
    BENE_SEX_IDENT_CD INT,
    BENE_RACE_CD INT,
    SP_STATE_CODE INT,
    BENE_COUNTY_CD INT,
    SP_ALZHDMTA INT,
    SP_CHF INT,
    SP_CHRNKIDN INT,
    SP_CNCR INT,
    SP_COPD INT,
    SP_DEPRESSN INT,
    SP_DIABETES INT,
    SP_ISCHMCHT INT,
    SP_OSTEOPRS INT,
    SP_RA_OA INT,
    SP_STRKETIA INT,
    Total_mons INT
);
